GoBundle\Entity\Utilisateur:
    type: entity
    table: Utilisateurs
    repositoryClass: GoBundle\Repository\UtilisateurRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
            nullable: true
        tel:
            type: integer
            nullable: true

        datedenaissance:
            type: date
            nullable: true
    lifecycleCallbacks: {  }
    oneToMany:
        attribution:
            targetEntity: Attribution
            mappedBy: utilisateur 