<?php

namespace GoBundle\Repository;

/**
 * CreneauRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreneauRepository extends \Doctrine\ORM\EntityRepository
{
}
