<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyn5oze\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyn5oze/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerYyn5oze.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerYyn5oze\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerYyn5oze\appDevDebugProjectContainer([
    'container.build_hash' => 'Yyn5oze',
    'container.build_id' => '145c7162',
    'container.build_time' => 1553170620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyn5oze');
