<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX1vvqvv\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX1vvqvv/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX1vvqvv.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX1vvqvv\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX1vvqvv\appDevDebugProjectContainer([
    'container.build_hash' => 'X1vvqvv',
    'container.build_id' => '960b26a2',
    'container.build_time' => 1553163687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX1vvqvv');
