<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKgkco4w\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKgkco4w/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKgkco4w.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKgkco4w\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKgkco4w\appDevDebugProjectContainer([
    'container.build_hash' => 'Kgkco4w',
    'container.build_id' => '7a66dfa6',
    'container.build_time' => 1553172257,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKgkco4w');
